Create tests for ProxyNetworkConfigDTO
GFLcourses3/group1 pull request #15
Opened 2023-03-02 17:19 UTC by antonRMNV

Tests for ProxyNetworkConfigDTO were created.

2023-03-02 18:09 UTC, Serhx4 requested changes

2023-03-02 18:09 UTC, Serhx4 commented on src/test/java/executor/service/model/ProxyNetworkConfigDTOTest.java
> +        proxyNetworkConfig1 = new ProxyNetworkConfigDTO("localhost", 8080);
@antonRMNV, we can improve our code by using constants for "magic" numbers and strings: `localhost`, `somehost`, `8080`, `80`.
These numbers and strings are used in almost every test, so good practice is to use constant fields for them.

2023-03-02 18:45 UTC, antonRMNV commented on src/test/java/executor/service/model/ProxyNetworkConfigDTOTest.java
> +        proxyNetworkConfig1 = new ProxyNetworkConfigDTO("localhost", 8080);
@Serhx4, ok, i'll improve this code by adding constants. Thanks.

2023-03-02 20:58 UTC, AlexandrTokarenko approved these changes

2023-03-03 08:45 UTC, artemkedyk commented on src/test/java/executor/service/model/ProxyNetworkConfigDTOTest.java
> +    private static final String LOCALHOST = "localhost";
```suggestion
    private final String LOCALHOST = "localhost";
```

2023-03-04 16:27 UTC, antonRMNV commented on src/test/java/executor/service/model/ProxyNetworkConfigDTOTest.java
> +    private static final String LOCALHOST = "localhost";
@artemkedyk, corrected. Thanks.

2023-03-04 17:13 UTC, Serhx4 approved these changes

2023-03-07 21:05 UTC, tatarynovdima approved these changes

2023-03-09 12:42 UTC, bielik-b approved these changes

2023-03-10 11:48 UTC, artemkedyk approved these changes

2023-03-10 19:24 UTC, merged