Migrate plug service scenario source listener to the spring
GFLcourses3/group1 pull request #52
Opened 2023-04-16 23:18 UTC by tatarynovdima

I wrote a Migrate, ScenarioSourceListener in Spring. But I ran into the error "Could not  @Autowired. No beans of 'ObjectMapper' type found.", which occurs because Spring cannot find an ObjectMapper bean that should be automatically created and registered in the Spring context. So I added the AppConfig class to the config package with @Configuration atonation to solve this error

2023-04-18 07:22 UTC, artemkedyk approved these changes

2023-04-18 11:03 UTC, Serhx4 requested changes
Hi, @tatarynovdima!
Looks like build was failed for this pull request.
It happened because you tried to merge Spring code into `main`.
Try to pull it into `spring` instead

2023-04-19 08:51 UTC, AlexandrTokarenko approved these changes

2023-04-19 10:42 UTC, artemkedyk commented on src/main/java/executor/service/service/ScenarioSourceListenerImpl.java
> +@Repository
let's use Service instead of Repository

2023-04-19 13:08 UTC, tatarynovdima commented
Thank @artemkedyk  you I have made changes

2023-04-19 13:20 UTC, Serhx4 approved these changes

2023-04-19 13:21 UTC, merged