Migrate ProxySourcesClient for working with HTTP
GFLcourses3/group1 pull request #68
Opened 2023-04-23 21:55 UTC by tatarynovdima

Migrate ProxySourcesClient for working with HTTP and Create test ProxySourcesClient for working with HTTP

2023-04-24 07:09 UTC, artemkedyk approved these changes

2023-04-24 07:44 UTC, AlexandrTokarenko approved these changes

2023-04-24 14:46 UTC, Serhx4 commented
Hi, @tatarynovdima 
Maybe you missed some commits here. There's no any http related functionality

2023-05-01 14:04 UTC, Serhx4 requested changes

2023-05-01 14:10 UTC, Serhx4 commented on src/main/java/executor/service/service/ProxySourcesClientImpl.java
> +            int status = con.getResponseCode();
We don't use this one field in code below

2023-05-01 14:19 UTC, tatarynovdima commented on src/main/java/executor/service/service/ProxySourcesClientImpl.java
> +            int status = con.getResponseCode();
In this case, although the code is not used directly, it can be used for logging or error handling if the connection failed or the server returned a response with an invalid status code. So this code can be useful for debugging and error handling.

2023-05-02 14:35 UTC, Serhx4 approved these changes

2023-05-02 15:23 UTC, merged