created WebDriverConfigDTO class
GFLcourses3/group1 pull request #9
Opened 2023-02-12 17:25 UTC by VatBane

2023-02-12 21:15 UTC, bielik-b approved these changes

2023-02-13 08:44 UTC, Serhx4 requested changes

2023-02-13 08:44 UTC, Serhx4 commented on src/main/java/executor/service/model/WebDriverConfigDTO.java
> +}
Please override equals and hashcode methods

2023-02-14 07:55 UTC, AlexandrTokarenko approved these changes

2023-02-14 07:55 UTC, closed without merging